plugins {
    id 'java'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

repositories {
    mavenCentral()
    maven { url = "https://repo.spongepowered.org/repository/maven-public/" }
    maven { url = "https://maven.fabricmc.net/" }
    maven { url = "https://maven.neoforged.net/releases/" }
}

dependencies {
    compileOnly 'org.spongepowered:mixin:0.8.5'
    compileOnly 'org.ow2.asm:asm-tree:9.7'
    
    compileOnly 'net.fabricmc:fabric-loader:0.16.9'
    
    compileOnly 'org.jetbrains:annotations:24.1.0'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesName}" }
    }
    
    exclude 'net/**'
    exclude 'org/**'
    
    manifest {
        attributes(
            'MixinConfigs': 'noslimesuperflat.mixins.json',
            'FMLCorePlugin': 'com.onyxi7.noslimesuperflat.platform.CorePlugin',
            'FMLCorePluginContainsFMLMod': 'true',
            'ForceLoadAsMod': 'true'
        )
    }
}
