plugins {
    id 'java'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

sourceSets {
    main {
        java {
            srcDir 'src/main/java-compile'
        }
    }
}

repositories {
    mavenCentral()
    maven { url = "https://repo.spongepowered.org/repository/maven-public/" }
    maven { url = "https://maven.fabricmc.net/" }
}

dependencies {
    compileOnly 'org.spongepowered:mixin:0.8.5'
    compileOnly 'org.ow2.asm:asm-tree:9.7'
    compileOnly 'net.fabricmc:fabric-loader:0.16.9'
    compileOnly 'org.jetbrains:annotations:24.1.0'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archives_base_name}" }
    }
    
    // Exclude ALL stub classes
    exclude 'net/**'
    exclude 'org/**'
    exclude 'com/onyxi7/noslimesuperflat/compile/**'
    
    manifest {
        attributes(
            'MixinConfigs': 'noslimesuperflat.mixins.json',
            'FMLCorePlugin': 'com.onyxi7.noslimesuperflat.platform.CorePlugin',
            'FMLCorePluginContainsFMLMod': 'true',
            'ForceLoadAsMod': 'true'
        )
    }
}

tasks.register('sourcesJar', Jar) {
    archiveClassifier = 'sources'
    from sourceSets.main.allSource
}

artifacts {
    archives sourcesJar
}
